apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  containers:
    - name: webapp
      image: 864798405299.dkr.ecr.sa-east-1.amazonaws.com/dale-repo/webapp:2e6e8191fad7434d2d9960f7751b1d20dfaa753d
      ports:
        - containerPort: 8080
