apiVersion: v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  containers:
    - name: webapp
      image: repositoryUrl/webapp:tagVersion
      ports:
        - containerPort: 8080